c_compiler:                # [win]
  - clang                  # [win]
c_compiler_version:        # [win]
  - 18                     # [win]
cxx_compiler:              # [win]
  - clangxx                # [win]
cxx_compiler_version:      # [win]
  - 18                     # [win]
